version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@palette.dev/browser'
      - dependency-name: '@palette.dev/webpack-plugin'
